const API=String(window.BATCH_OS_CONFIG?.apiBase||'').replace(/\/$/,'');
const $=id=>document.getElementById(id); const state={recipes:[],filtered:[],selected:null,plan:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2}); const vol=l=>l>=1?`${fmt(l)} L`:`${fmt(l*33.814)} oz`;
async function api(path,opts){const r=await fetch(`${API}${path}`,opts);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||`HTTP ${r.status}`);return r.json()}
async function load(){try{const d=await api('/api/recipes');state.recipes=d.recipes;state.filtered=d.recipes;$('recipeCount').textContent=d.totalCount;$('status').textContent=`API online · ${d.totalCount} recipes`;
 [...new Set(d.recipes.map(r=>r.category).filter(Boolean))].sort().forEach(v=>$('category').insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));renderList()}catch(e){$('status').textContent=`API unavailable · ${e.message}`}}
function renderList(){const q=$('search').value.trim().toLowerCase(),cat=$('category').value;state.filtered=state.recipes.filter(r=>(!q||[r.name,r.category,r.method,...(r.ingredients||[]).map(i=>i.ingredient)].join(' ').toLowerCase().includes(q))&&(!cat||r.category===cat));$('recipeList').innerHTML=state.filtered.map((r,i)=>`<button class="recipe-item ${state.selected?.name===r.name?'active':''}" data-i="${i}"><strong>${esc(r.name)}</strong><span>${esc(r.category||'—')} · ${esc(r.method||'—')}</span></button>`).join('');document.querySelectorAll('.recipe-item').forEach(b=>b.onclick=()=>select(state.filtered[Number(b.dataset.i)]))}
function select(r){state.selected=r;state.plan=null;$('empty').hidden=true;$('planner').hidden=false;$('results').hidden=true;$('recipeMeta').textContent=r.category||'COCKTAIL';$('recipeName').textContent=r.name;$('recipeService').textContent=`${r.method||'—'} · ${r.glass||'—'} · ${r.ice||'—'} · Garnish: ${r.garnish||'—'}`;renderList()}
function payload(){return{recipeName:state.selected.name,guests:+$('guests').value,drinksPerGuest:+$('drinks').value,menuSharePct:+$('share').value,overagePct:+$('overage').value,dilutionPct:+$('dilution').value,bottleSizeMl:+$('bottle').value,vesselSize:+$('vessel').value,vesselUnit:$('vesselUnit').value}}
async function calculate(){if(!state.selected)return;const b=$('calculate');b.disabled=true;b.textContent='Calculating…';try{const p=await api('/api/batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())});state.plan=p;renderPlan(p)}catch(e){alert(`Batch calculation failed: ${e.message}`)}finally{b.disabled=false;b.textContent='Generate batch plan'}}
function renderPlan(p){$('results').hidden=false;$('pours').textContent=fmt(p.summary.plannedPours);$('base').textContent=vol(p.summary.baseLiters);$('water').textContent=vol(p.summary.dilutionLiters);$('yield').textContent=vol(p.summary.finalLiters);$('vessels').textContent=`${p.summary.vesselCount} × ${fmt(p.summary.vesselLiters)} L`;$('ingredients').innerHTML=p.ingredients.map(i=>`<tr><td><strong>${esc(i.ingredient)}</strong></td><td>${fmt(i.perDrinkOz)} oz</td><td>${fmt(i.totalLiters)} L</td><td>${i.bottlesToBuy} × ${fmt(i.bottleSizeMl)} mL</td></tr>`).join('')||'<tr><td colspan="4">No safely batchable liquid ingredients.</td></tr>';$('prep').innerHTML=p.prepItems.map(i=>`<div class="note"><strong>${esc(i.ingredient)}</strong> · ${esc(i.amount||'manual')}<br><span class="muted">${esc(i.note||'Prep separately.')}</span></div>`).join('')||'<div class="note">No separate prep items detected.</div>';$('warnings').innerHTML=p.warnings.map(i=>`<div class="note warn"><strong>${esc(i.ingredient)}</strong> · ${esc(i.amount||'—')}<br>${esc(i.note)}</div>`).join('')||'<div class="note">No source-data warnings detected.</div>';}
function copyPlan(){if(!state.plan)return;const p=state.plan;const lines=[`BATCH OS — ${p.recipe.name}`,`${p.summary.plannedPours} pours · ${fmt(p.summary.finalLiters)} L final yield`,...p.ingredients.map(i=>`${i.ingredient}: ${fmt(i.totalLiters)} L (${i.bottlesToBuy} × ${fmt(i.bottleSizeMl)} mL bottles)`),`Dilution water: ${fmt(p.summary.dilutionLiters)} L`,`Vessels: ${p.summary.vesselCount} × ${fmt(p.summary.vesselLiters)} L`,`Service: ${p.recipe.method} · ${p.recipe.glass} · ${p.recipe.ice} · ${p.recipe.garnish}`];navigator.clipboard.writeText(lines.join('\n')).then(()=>{$('copy').textContent='Copied';setTimeout(()=>$('copy').textContent='Copy',1200)})}
$('search').oninput=renderList;$('category').onchange=renderList;$('calculate').onclick=calculate;$('copy').onclick=copyPlan;$('print').onclick=()=>window.print();load();
