[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "https://cryptococktailclub.com/"
  to = "/litepaper/index.html"
  status = 200

[[redirects]]
  from = "https://cryptococktailclub.com/*"
  to = "/litepaper/:splat"
  status = 200

[[redirects]]
  from = "https://cryptococktail.club/backroom"
  to = "https://cryptococktailclub.com/member/"
  status = 302
  force = true

[[redirects]]
  from = "https://cryptococktail.club/backroom/*"
  to = "https://cryptococktailclub.com/member/"
  status = 302
  force = true

[[redirects]]
  from = "https://cryptococktail.club/*"
  to = "/:splat"
  status = 200
